# Generated by Django 5.0.3 on 2024-03-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animais',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('raca', models.TextField(max_length=255)),
            ],
        ),
    ]
