# Generated by Django 5.0.3 on 2024-03-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('raça', models.TextField(max_length=255)),
                ('gênero', models.TextField(max_length=255)),
                ('imagem', models.ImageField(upload_to='projeto_abrigo_amigo/app_abrigo_amigo/fotos')),
            ],
        ),
    ]
