# Generated by Django 5.0.4 on 2024-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abrigo_amigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='imagem',
            field=models.ImageField(default='default_image.jpg', upload_to='fotos/'),
        ),
    ]
