# Generated by Django 5.0.3 on 2024-03-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abrigo_amigo', '0002_rename_raca_animais_raça'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='gênero',
            field=models.TextField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
