# Generated by Django 5.0.4 on 2024-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abrigo_amigo', '0002_animais_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='imagem',
            field=models.FileField(default='default_image.jpg', upload_to='fotos/'),
        ),
    ]
