# Generated by Django 5.0.4 on 2024-04-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_abrigo_amigo', '0003_alter_animais_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animais',
            name='imagem',
        ),
    ]
