# Generated by Django 5.0.6 on 2024-06-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abrigo_amigo', '0004_remove_animais_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='animais',
            name='gênero',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AlterField(
            model_name='animais',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animais',
            name='raça',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animais',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
